trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApp
  displayName: Stage1
  jobs:
  - job: BuildFrontendApp
    displayName: Job1
    steps:
    - script: echo building frontend app
      displayName: step1
    - script: echo running unit tests for frontend app
      displayName: step2

  - job: BuildBackendApp
    displayName: job2
    steps:
    - script: echo building backend app
      displayName: step1
    - script: echo running unit tests for backend app
      displayName: step2

- stage: DeployDev
  displayName: Stage2
  jobs:
  - job: DeployFrontendDev
    displayName: job1
    steps:
    - script: echo deploying frontend app to DEV
      displayName: step1

  - job: DeployBackendDev
    displayName: job2
    steps:
    - script: echo deploying backend app to DEV
      displayName: step1

- stage: DeployProd
  displayName: Stage3
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: DeployFrontendProd
    displayName: job1
    steps:
    - script: echo deploying frontend app to PROD
      displayName: step1

  - job: DeployBackendProd
    displayName: job2
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo deploying backend app to PROD
      displayName: step1